const vocabData = [
  { unit: 1, word: "Patient", meaning: "Prepared to wait / able to stay calm." },
  { unit: 1, word: "Strict", meaning: "Someone who thinks rules must be followed." },
  { unit: 1, word: "Bright", meaning: "Quick to understand and very smart." },
  { unit: 2, word: "Reliable", meaning: "That can be trusted to do something well." },
  { unit: 2, word: "Exclusive", meaning: "Only the richest or best people can use it." },
  { unit: 2, word: "Exquisite", meaning: "Extremely beautiful and delicate." },
  { unit: 3, word: "Inquire", meaning: "To ask for information in a polite or formal way." },
  { unit: 3, word: "Illustrate", meaning: "To show or explain something clearly with an example." },
  { unit: 3, word: "Appreciate", meaning: "To understand and enjoy the value of something." },
  { unit: 4, word: "Fulfillment", meaning: "Feeling happy because your work is useful." },
  { unit: 4, word: "Distracted", meaning: "Not able to focus because you are thinking about something else." },
  { unit: 4, word: "Exploiting", meaning: "Using someone unfairly for your own advantage." },
  { unit: 5, word: "Trait", meaning: "a particular quality in your personality or body" },
  { unit: 5, word: "Spectator", meaning: "a person who watches a sport or an event" },
  { unit: 5, word: "Explores", meaning: "to examine or talk about something to learn more" },
  { unit: 5, word: "Fascinating", meaning: "extremely interesting" },
  { unit: 5, word: "Sedentary", meaning: "spending a lot of time sitting down and not moving" },
  { unit: 5, word: "Opting", meaning: "choosing one thing instead of another" },
  { unit: 5, word: "Massive", meaning: "very, very big or powerful" },
  { unit: 5, word: "Cited", meaning: "mentioned as an example or a reason" },
  { unit: 5, word: "Simplicity", meaning: "the quality of being easy to understand or do" },
  { unit: 5, word: "Unpredictability", meaning: "the quality of being difficult to know what will happen next" },
  { unit: 5, word: "Cherish", meaning: "to love and keep something as a very important thing" },
  { unit: 5, word: "Stakes", meaning: "the money or risk involved in a game or event" },
  { unit: 5, word: "Constantly", meaning: "all the time or very often" },
  { unit: 5, word: "Evolving", meaning: "changing and developing slowly over time" },
  { unit: 5, word: "Overlooked", meaning: "not noticed or not thought to be important" },
  { unit: 5, word: "Staple", meaning: "a main or very important part of a culture or diet" },
  { unit: 5, word: "Immense", meaning: "extremely large or great" },
  { unit: 5, word: "Concentration", meaning: "the ability to think carefully about one thing" },
  { unit: 5, word: "Ultimately", meaning: "used to emphasize the most important or final result" },
  { unit: 6, word: "incredibly", meaning: "Very, very much; used to emphasize that something is extremely good, large, or surprising." },
  { unit: 6, word: "depressing", meaning: "Making you feel very sad and without any hope for the future." },
  { unit: 6, word: "pint", meaning: "A unit for measuring liquids, especially milk or beer (about 0.5 liters)." },
  { unit: 6, word: "complicated", meaning: "Difficult to understand or deal with because it has many different parts." },
  { unit: 7, word: "Hiccups", meaning: "A loud noise you make in your throat without wanting to, often caused by eating or drinking too fast." },
  { unit: 7, word: "Indigestion", meaning: "Pain or discomfort in your stomach when it is difficult to digest food." },
  { unit: 7, word: "Stitches", meaning: "Small loops of thread used by a doctor to close a deep cut in the skin." },
  { unit: 7, word: "Infection", meaning: "A disease caused by germs or bacteria entering the body or a wound." },
  { unit: 7, word: "Depression", meaning: "A mental health condition where a person feels very sad, tired, and hopeless for a long time." },
  { unit: 8, word: "Ongoing", meaning: "Continuing to exist or develop; happening right now." },
  { unit: 8, word: "Lorry", meaning: "A large, heavy motor vehicle used for transporting goods; a truck." },
  { unit: 8, word: "Diversion", meaning: "A different route that is used because a road is closed." },
  { unit: 8, word: "Monument", meaning: "A statue or building built to help people remember a famous person or event." },
  { unit: 8, word: "Frustration", meaning: "The feeling of being annoyed or upset because you cannot change or achieve something." },
  { unit: 8, word: "Perspective", meaning: "A particular way of thinking about something; a point of view." },
  { unit: 9, word: "Extinct", meaning: "When a type of animal or plant has died out and no longer exists in the world." },
  { unit: 9, word: "Pollination", meaning: "The process where pollen is moved to a flower so that it can make new seeds." },
  { unit: 9, word: "Defy", meaning: "To be very different from what people usually expect or believe is possible." },
  { unit: 9, word: "Reputations", meaning: "The general opinions or ideas that people have about someone or something." },
  { unit: 9, word: "Incredible", meaning: "Something that is so amazing, large, or good that it is difficult to believe." },
  { unit: 9, word: "Detect", meaning: "To find or notice something that is hidden or very difficult to see." },
  { unit: 9, word: "Explode", meaning: "To burst suddenly with a very loud noise and cause a lot of damage." },
  { unit: 9, word: "Interaction", meaning: "The way that two things communicate with each other or work together." },
  { unit: 9, word: "Persuade", meaning: "To make someone agree to do something by giving them good reasons." },
  { unit: 9, word: "Pivotal", meaning: "Extremely important because other things depend on it to be successful." },
  { unit: 9, word: "Conducted", meaning: "To have organized and performed a specific task, such as an experiment or a test." },
  { unit: 9, word: "Impulse", meaning: "A sudden and strong feeling that you must do something immediately." },
  { unit: 9, word: "Override", meaning: "To be more important than someone else's opinion and change their decision." },
  { unit: 10, word: "Significantly", meaning: "In a way that is large or important enough to be noticed." },
  { unit: 10, word: "Plagiarism", meaning: "Copying someone else's words or ideas and pretending they are your own." },
  { unit: 10, word: "Sophisticated", meaning: "Very advanced and using complex ideas or modern technology." },
  { unit: 10, word: "Contemplating", meaning: "Thinking deeply or carefully about something for a long time." },
  { unit: 10, word: "Encountering", meaning: "Experiencing or meeting something, especially a problem or a challenge." },
  { unit: 10, word: "Theoretical", meaning: "Based on ideas and rules rather than on practical experience or use." },
  { unit: 10, word: "Temptation", meaning: "A strong feeling that you want to do something, even if you know it is wrong." },
  { unit: 10, word: "Embrace", meaning: "To eagerly accept a new idea, opinion, or way of doing something." },
  { unit: 11, word: "Crucial", meaning: "Extremely important or necessary for the success or failure of something." },
  { unit: 11, word: "Entirely", meaning: "Completely; with nothing missing or excepted." },
  { unit: 11, word: "Bustling", meaning: "Full of people moving about in a busy way; very active." },
  { unit: 11, word: "Nomadic", meaning: "Belonging to a group of people who move from place to place rather than living in one place all the time." },
  { unit: 11, word: "Self-proclaimed", meaning: "Giving yourself a particular title or status without anyone else saying it is true." },
  { unit: 11, word: "Pollution", meaning: "Substances that make air, water, or soil dirty and dangerous for living things." },
  { unit: 11, word: "Fondly", meaning: "In a way that shows love or great liking for someone or something." },
  { unit: 11, word: "Atmosphere", meaning: "The feeling or mood that you get from a particular place or situation." },
  { unit: 11, word: "Vibe", meaning: "The general mood or emotional quality of a person, place, or situation (informal)." },
  { unit: 11, word: "Convenient", meaning: "Useful, easy, or quick to do; not causing any problems." },
  { unit: 11, word: "Deposit", meaning: "A sum of money that is given as the first part of a larger payment to secure a booking." },
  { unit: 11, word: "Presidential", meaning: "Relating to a president, or suitable for a president (often used for luxury hotel suites)." },
  { unit: 11, word: "Severe", meaning: "Very serious, bad, or difficult to deal with." },
  { unit: 11, word: "Arranging", meaning: "Putting things in a particular order or position, especially to make them look attractive." },
  { unit: 11, word: "Nostalgia", meaning: "A feeling of pleasure mixed with sadness when you think of happy times in the past." },
  { unit: 11, word: "Maintenance", meaning: "The act of keeping something in good condition (High-maintenance: needing a lot of time, money, or effort)." },
  { unit: 11, word: "Reflects", meaning: "To show, express, or be a sign of something." },
  { unit: 12, word: "Urgent", meaning: "Very important and needing to be dealt with immediately." },
  { unit: 12, word: "Literally", meaning: "Used to emphasize that something is actually true, even if it sounds surprising." },
  { unit: 12, word: "Trivial", meaning: "Not important or serious; having very little value." },
  { unit: 12, word: "Improper", meaning: "Not right or not suitable for a particular situation; dishonest." },
  { unit: 12, word: "Leaflets", meaning: "Small pieces of printed paper that give information or advertise something." },
  { unit: 12, word: "Swelling", meaning: "A place on your body that has become larger than normal because of an injury or illness." },
  { unit: 12, word: "Presence (of mind)", meaning: "The ability to stay calm and make good decisions in a difficult or surprising situation." },
  { unit: 12, word: "Experts", meaning: "People who have a lot of knowledge or skill in a particular subject." },
  { unit: 12, word: "Identified", meaning: "Recognized or named someone or something correctly." },
  { unit: 12, word: "Species", meaning: "A group of animals or plants that are very similar to each other." },
  { unit: 12, word: "Postage", meaning: "The amount of money you pay to send a letter or a package by mail." },
  { unit: 12, word: "Defines", meaning: "Describes or explains the quality or nature of something." },
  { unit: 13, word: "Rehearsing", meaning: "Practising a play, a piece of music, or a dance before performing it in front of an audience." },
  { unit: 13, word: "Obsessed", meaning: "Thinking about someone or something all the time and being unable to think about anything else." },
  { unit: 13, word: "Predictable", meaning: "Happening in a way that is expected and not at all surprising." },
  { unit: 13, word: "Frightened", meaning: "Feeling afraid or anxious because you think something bad or dangerous might happen." },
  { unit: 13, word: "Brilliant", meaning: "Extremely clever or highly skilled; another word for very good or excellent." },
  { unit: 13, word: "Extraordinary", meaning: "Very unusual, special, or much better than the usual level." },
  { unit: 13, word: "Exhibition", meaning: "A public event where objects such as paintings or sculptures are shown for people to look at." },
  { unit: 14, word: "Rubbish", meaning: "Things that are no longer wanted or needed and are thrown away; waste material." },
  { unit: 14, word: "Bleach", meaning: "A strong chemical liquid used for cleaning and for making things white or removing stains." },
  { unit: 14, word: "Kettle", meaning: "A metal or plastic container with a lid and handle, used for boiling water to make tea or coffee." },
  { unit: 14, word: "Precious", meaning: "Very valuable or important to someone, often because of sentimental or emotional reasons." },
  { unit: 14, word: "Dioxide (Carbon)", meaning: "A gas without color or smell that is produced when things are burned or when we breathe out." },
  { unit: 14, word: "Biodegradable", meaning: "Able to decay naturally and be changed into a harmless form by bacteria, without damaging the environment." },
  { unit: 14, word: "Archaeologists", meaning: "People who study human history by digging up and examining objects and buildings from the past." },
  { unit: 14, word: "Preserved", meaning: "Kept in its original state or in good condition for a long time by preventing it from decaying." },
  { unit: 14, word: "Responsibility", meaning: "Something that it is your job or duty to deal with or take care of." },
  { unit: 15, word: "Climate", meaning: "The general situation or set of conditions in a particular area." },
  { unit: 15, word: "Unemployment", meaning: "The state of not having a job, or the number of people without work." },
  { unit: 15, word: "Accumulate", meaning: "To gradually collect or increase in amount over a period of time." },
  { unit: 15, word: "Persistent", meaning: "Continuing to do something or exist for a long time, especially despite difficulties." },
  { unit: 15, word: "Frugality", meaning: "The habit of being careful with money and avoiding waste." },
  { unit: 15, word: "Staggering", meaning: "Very shocking or surprising because of being so large or unusual." },
  { unit: 15, word: "Impoverished", meaning: "Extremely poor; lacking the money or resources needed for a good life." },
  { unit: 15, word: "Extraordinarily", meaning: "In a way that is very unusual, special, or much greater than normal." },
  { unit: 15, word: "Shrewd", meaning: "Good at making practical decisions, especially in business or financial matters." },
  { unit: 15, word: "Astonished", meaning: "Feeling very surprised or amazed by something." },
  { unit: 15, word: "Inheritances", meaning: "Money, property, or assets received from someone who has died." },
  { unit: 15, word: "Charity", meaning: "An organization that collects money to help people in need." },
  { unit: 15, word: "Demonstrate", meaning: "To show or prove something clearly by giving examples or evidence." },
  { unit: 15, word: "Transactions", meaning: "The process of buying or selling something; business deals." },
  { unit: 15, word: "Mundane", meaning: "Ordinary and not interesting or exciting." },
  { unit: 15, word: "Complications", meaning: "Problems or difficulties that make a situation more complex." },
  { unit: 15, word: "Bargaining", meaning: "Discussing the price of something to try to make it cheaper." },
  { unit: 15, word: "Fares", meaning: "The money paid for a journey on public transport (bus, train, etc.)." },
  { unit: 15, word: "Caution", meaning: "Care taken to avoid danger or mistakes." },
  { unit: 15, word: "Suspected", meaning: "Believed to be true or likely, but without certain proof." },
  { unit: 16, word: "Significant", meaning: "Important or large enough to be noticed." },
  { unit: 16, word: "Remarkable", meaning: "Very unusual or surprising in a way that people notice." },
  { unit: 16, word: "Shifts", meaning: "Changes in position, direction, or the way someone thinks." },
  { unit: 16, word: "Existence", meaning: "The state of being real or living." },
  { unit: 16, word: "Vast", meaning: "Extremely big or wide." },
  { unit: 16, word: "Transition", meaning: "A process of changing from one system or condition to another." },
  { unit: 16, word: "Evolved", meaning: "Changed or developed slowly over a long time." },
  { unit: 16, word: "Agriculture", meaning: "The work of farming and growing crops or keeping animals." },
  { unit: 16, word: "Drastic", meaning: "Sudden, severe, or having a very big effect." },
  { unit: 16, word: "Undergo", meaning: "To experience something, especially a change or something difficult." },
  { unit: 16, word: "Milestones", meaning: "Very important events in the history of something or someone's life." },
  { unit: 16, word: "Coincide", meaning: "To happen at the same time as something else." },
  { unit: 16, word: "Broader", meaning: "Including a wider range of things or ideas." },
  { unit: 16, word: "Contexts", meaning: "The situations or information that help you understand something." },
  { unit: 16, word: "Segregation", meaning: "Keeping people of different races or groups separate from each other." },
  { unit: 16, word: "Racial", meaning: "Relating to people's race (the group they belong to based on skin color)." },
  { unit: 16, word: "Commemorating", meaning: "Doing something to show that you remember and respect an important person or event." },
  { unit: 16, word: "Fundamental", meaning: "Basic and most important." },
  { unit: 16, word: "Mourn", meaning: "To feel very sad because someone has died." },
  { unit: 16, word: "Tragedy", meaning: "A very sad event, often involving death or great suffering." },
  { unit: 16, word: "Regret", meaning: "To feel sorry about something you did or did not do in the past." },
  { unit: 16, word: "Commit", meaning: "To promise to do something or to give your time to something." },
  { unit: 16, word: "Determination", meaning: "The desire to continue trying to do something even if it is difficult." },
  { unit: 16, word: "Chronic", meaning: "(Especially of an illness) lasting for a long time and difficult to cure." },
  { unit: 16, word: "Converted", meaning: "Changed from one form or use to another." },
  { unit: 16, word: "Aubergines", meaning: "Purple vegetables with white flesh (also called eggplants)." },
  { unit: 16, word: "Awkward", meaning: "Making you feel embarrassed or uncomfortable." },
  { unit: 16, word: "Encounter", meaning: "A meeting, especially one that is sudden or unexpected." },
  { unit: 16, word: "Anecdotes", meaning: "Short, interesting, or funny stories about a real person or event." },
  { unit: 16, word: "Contributes", meaning: "To help to cause or develop something." },
  { unit: 16, word: "Reflecting", meaning: "Thinking carefully and deeply about something." },
  { unit: 16, word: "Intricate", meaning: "Having a lot of small parts or details put together in a complex way." },
  { unit: 16, word: "Tapestry", meaning: "A piece of thick cloth with pictures or designs sewn on it; used here to mean a complex situation." },
];